# Generated by Django 5.2.7 on 2025-10-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_predictionrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('procedure_type', models.CharField(choices=[('surgical', 'Surgical Operation'), ('non_surgical', 'Non-Surgical Treatment')], max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='amount',
            new_name='final_amount',
        ),
        migrations.AddField(
            model_name='patient',
            name='handicapped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='insurance_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='daily_care_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='payment',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='procedure_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='total_before_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='procedures',
            field=models.ManyToManyField(blank=True, to='api.procedure'),
        ),
    ]
