# Generated by Django 5.2.7 on 2025-10-10 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_procedure_rename_amount_payment_final_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10, unique=True)),
                ('room_type', models.CharField(default='General', max_length=50)),
                ('bed_capacity', models.PositiveIntegerField(default=1)),
                ('occupied_beds', models.PositiveIntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='admission',
            name='doctor_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='requires_inpatient',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='admission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending (Waiting for Doctor)'), ('admitted', 'Admitted (Inpatient)'), ('pending_discharge', 'Pending Discharge (Waiting for Payment)'), ('discharged', 'Discharged')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='admission',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.room'),
        ),
    ]
