# Generated by Django 5.2.7 on 2025-10-11 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_room_admission_doctor_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='admission_status',
        ),
    ]
