# Generated by Django 5.2.7 on 2025-11-06 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_patient_a1cresult_norm_patient_a1cresult_gt8_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='procedures',
            field=models.ManyToManyField(blank=True, related_name='admissions', to='api.procedure'),
        ),
    ]
