# Generated by Django 5.2.7 on 2025-11-07 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_admission_procedures'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='nhs_number',
            field=models.CharField(blank=True, help_text='10-digit NHS number', max_length=10, null=True, unique=True),
        ),
    ]
