# Generated by Django 5.2.7 on 2025-11-29 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_medicine_alter_user_role_pharmacystaff_prescription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='procedures',
            field=models.ManyToManyField(blank=True, related_name='appointments', to='api.procedure'),
        ),
        migrations.AddField(
            model_name='payment',
            name='appointments',
            field=models.ManyToManyField(blank=True, related_name='payments', to='api.appointment'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('inpatient', 'Inpatient (Admission)'), ('outpatient', 'Outpatient (Appointments)')], default='inpatient', max_length=20),
        ),
        migrations.AddField(
            model_name='prescription',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='api.appointment'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='admission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.admission'),
        ),
    ]
