# Generated by Django 5.2.7 on 2025-12-05 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_appointment_options_appointment_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
