# Generated by Django 5.2.7 on 2025-12-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_patient_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nurse',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pharmacystaff',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
